-- ═══════════════════════════════════════════════════════════════
-- OSS Seed Data — run manually: psql -f seed.sql
-- Assumes the schema from init.sql already exists (page_id = 1 for home).
-- ═══════════════════════════════════════════════════════════════

-- ── Fields (Nos domaines d'action) ──
INSERT INTO fields (page_id, title_fr, title_en, description_fr, description_en, image, gradient_hue, sort_order, is_published) VALUES
  (1,
   'Eau', 'Water',
   'Gestion durable des ressources en eau dans les zones arides et semi-arides du Sahara et du Sahel.',
   'Sustainable management of water resources in the arid and semi-arid zones of the Sahara and Sahel.',
   '/eau.jpg', 200, 1, true),

  (1,
   'Terre', 'Land',
   'Lutte contre la dégradation des terres et la désertification pour préserver les moyens de subsistance des populations.',
   'Combating land degradation and desertification to preserve the livelihoods of populations.',
   '/terre.jpg', 30, 2, true),

  (1,
   'Climat', 'Climate',
   'Adaptation au changement climatique et renforcement de la résilience des communautés et des écosystèmes.',
   'Adaptation to climate change and strengthening the resilience of communities and ecosystems.',
   '/climat.jpg', 10, 3, true),

  (1,
   'Biodiversité', 'Biodiversity',
   'Protection du patrimoine biologique et promotion d''une gestion intégrée des écosystèmes en Afrique.',
   'Protecting biological heritage and promoting integrated ecosystem management in Africa.',
   '/terre.jpg', 140, 4, true);


-- ── News (Actualités) ──
INSERT INTO news (title_fr, title_en, body_fr, body_en, images, thumbnail_index, date, slug, is_published) VALUES
  ('L''OSS et l''ICARDA renforcent leur coopération en faveur des zones arides',
   'OSS and ICARDA strengthen cooperation in favor of drylands',
   'L''Observatoire du Sahara et du Sahel (OSS) et le Centre international de recherche agricole dans les zones arides (ICARDA) ont renforcé leur coopération afin de répondre aux défis communs liés à la gestion durable des ressources naturelles dans les zones arides d''Afrique. Ce partenariat vise à développer des approches innovantes pour l''adaptation au changement climatique et la lutte contre la désertification.',
   'The Sahara and Sahel Observatory (OSS) and the International Center for Agricultural Research in the Dry Areas (ICARDA) have strengthened their cooperation to address common challenges related to sustainable natural resource management in Africa''s drylands. This partnership aims to develop innovative approaches for climate change adaptation and combating desertification.',
   '["/act1.jpg"]', 0, '2025-01-15', 'oss-icarda-cooperation-zones-arides', true),

  ('L''OSS a pris part à la session de renforcement et de mobilisation des financements pour promouvoir l''agroécologie',
   'OSS took part in the session on strengthening and mobilizing financing to promote agroecology',
   'L''OSS a participé activement à la session dédiée au renforcement des capacités et à la mobilisation des financements en faveur de l''agroécologie. Cette initiative s''inscrit dans le cadre des efforts continus de l''Observatoire pour promouvoir des pratiques agricoles durables et résilientes face aux défis environnementaux en Afrique.',
   'OSS actively participated in the session dedicated to capacity building and financing mobilization in favor of agroecology. This initiative is part of the Observatory''s ongoing efforts to promote sustainable and resilient agricultural practices in the face of environmental challenges in Africa.',
   '["/act2.jpg"]', 0, '2025-01-10', 'oss-session-mobilisation-financements-agroecologie', true),

  ('De l''engagement à l''action : renforcer la résilience climatique en Guinée-Bissau',
   'From commitment to action: strengthening climate resilience in Guinea-Bissau',
   'En collaboration avec ses partenaires, l''OSS accompagne la Guinée-Bissau dans le renforcement de sa résilience climatique. Ce projet illustre la transition d''engagements politiques vers des actions concrètes sur le terrain, intégrant les communautés locales dans l''adaptation aux impacts du changement climatique.',
   'In collaboration with its partners, OSS supports Guinea-Bissau in strengthening its climate resilience. This project illustrates the transition from political commitments to concrete actions on the ground, integrating local communities in adapting to the impacts of climate change.',
   '["/act3.jpg"]', 0, '2025-01-05', 'engagement-action-resilience-climatique-guinee-bissau', true),

  ('Deuxième réunion du Comité de pilotage du processus d''élaboration du premier rapport national sur la mise en œuvre du Protocole de Nagoya en Tunisie',
   'Second meeting of the Steering Committee for the development of the first national report on the implementation of the Nagoya Protocol in Tunisia',
   'La deuxième réunion du Comité de pilotage s''est tenue pour faire le point sur l''avancement du processus d''élaboration du premier rapport national tunisien sur la mise en œuvre du Protocole de Nagoya. Les participants ont examiné les progrès réalisés et défini les prochaines étapes pour finaliser ce rapport stratégique.',
   'The second Steering Committee meeting was held to review progress on developing Tunisia''s first national report on the implementation of the Nagoya Protocol. Participants examined the progress made and defined the next steps to finalize this strategic report.',
   '["/act4.jpg"]', 0, '2024-12-20', 'comite-pilotage-rapport-national-protocole-nagoya-tunisie', true);


-- ── Partners (top row = row_number 1, bottom row = row_number 2) ──
INSERT INTO partners (page_id, name, image, row_number, sort_order, is_published) VALUES
  -- Top row
  (1, 'Adaptation Fund',                '/logo/adaptation-fund.png', 1, 1, true),
  (1, 'Green Climate Fund',            '/logo/green-climate-fund.png', 1, 2, true),
  (1, 'GEF',                           '/logo/gef.avif', 1, 3, true),
  (1, 'FFEM',                          '/logo/ffem.webp', 1, 4, true),
  (1, 'World Bank',                    '/logo/world-bank.webp', 1, 5, true),
  (1, 'African Union',                 '/logo/african-union.png', 1, 6, true),
  (1, 'African Development Bank',      '/logo/african-development-bank.png', 1, 7, true),
  (1, 'African Water Facility',        '/logo/awf.png', 1, 8, true),
  (1, 'UNEP',                          '/logo/unep.png', 1, 9, true),

  -- Bottom row
  (1, 'COOP',                          '/logo/coop.png', 2, 1, true),
  (1, 'GIZ',                           '/logo/giz.png', 2, 2, true),
  (1, 'Ministère de l''Environnement du Climat et de la Biodiversité', '/logo/luxembourg-environment.png', 2, 3, true),
  (1, 'Swiss Confederation',           '/logo/swiss-confederation.svg', 2, 4, true),
  (1, 'European Union',               '/logo/european-union.svg', 2, 5, true),
  (1, 'Europe et Étranger',           '/logo/europe-foreign-affairs.jpg', 2, 6, true),
  (1, 'Ministère de la Transition Écologique et Solidaire', '/logo/france-ecological-transition.svg', 2, 7, true),
  (1, 'AFD',                           '/logo/afd.png', 2, 8, true);


-- ── Tools (Nos outils) ──
INSERT INTO tools (page_id, title_fr, title_en, description_fr, description_en, image, link, sort_order, is_published) VALUES
  (1, 'MISLAND', 'MISLAND',
   'Un système intégré de surveillance de la dégradation des terres utilisant des données d''observation de la Terre pour fournir des informations.',
   'An integrated land degradation surveillance system using Earth observation data to provide information.',
   '/misland.jpg', 'http://misland-africa.oss-online.org', 1, true),

  (1, 'MISBAR', 'MISBAR',
   'Un système de suivi et de contrôle des aires irriguées, basé sur des données spatiales à haute résolution.',
   'A monitoring and control system for irrigated areas, based on high-resolution spatial data.',
   '/misbar.jpg', 'http://misbar.oss-online.org/', 2, true),

  (1, 'SAP-MR Complexe WAP', 'SAP-MR WAP Complex',
   'Un outil pour anticiper et gérer les risques liés à la sécheresse, aux inondations, aux feux de végétation et aux conflits homme-faune dans le complexe W-Arly-Pendjari.',
   'A tool for anticipating and managing risks related to drought, flooding, vegetation fires and human-wildlife conflicts in the W-Arly-Pendjari complex.',
   '/wap.jpg', 'http://sapmr.oss-online.org', 3, true),

  (1, 'Copernicea', 'Copernicea',
   'Une plateforme de mesure et de suivi du capital naturel et de la résilience des écosystèmes aux niveaux continental, national et local.',
   'A platform for measuring and monitoring natural capital and ecosystem resilience at continental, national and local levels.',
   '/copernicea.webp', 'http://copernicea.oss-online.org', 4, true),

  (1, 'Umbrella Seychelles', 'Umbrella Seychelles',
   'Une plateforme d''aide à la décision dédiée aux acteurs seychellois, pour la planification et le suivi de la neutralité de la dégradation des terres (NDT) à l''échelle nationale.',
   'A decision-support platform dedicated to Seychellois stakeholders, for planning and monitoring Land Degradation Neutrality (LDN) at the national scale.',
   '/umbrella-sych.webp', 'https://umbrella-sych.oss-online.org/', 5, true),

  (1, 'Umbrella Libya', 'Umbrella Libya',
   'Une plateforme d''aide à la décision dédiée aux acteurs libyens, pour la planification et le suivi de la neutralité de la dégradation des terres (NDT) à l''échelle nationale.',
   'A decision-support platform dedicated to Libyan stakeholders, for planning and monitoring Land Degradation Neutrality (LDN) at the national scale.',
   '/umbrella-lyb.webp', 'https://umbrella-lyb.oss-online.org/', 6, true),

  (1, 'Umbrella Tunisia', 'Umbrella Tunisia',
   'Une plateforme d''aide à la décision dédiée aux acteurs tunisiens, pour la planification et le suivi de la neutralité de la dégradation des terres (NDT) à l''échelle nationale.',
   'A decision-support platform dedicated to Tunisian stakeholders, for planning and monitoring Land Degradation Neutrality (LDN) at the national scale.',
   '/umbrella-tun.webp', 'https://umbrella-tun.oss-online.org/', 7, true),

  (1, 'LDN Africa', 'LDN Africa',
   'Une plateforme panafricaine d''aide à la décision, fournissant à l''ensemble des pays du continent des outils de planification et de suivi pour atteindre la neutralité de la dégradation des terres (NDT).',
   'A pan-African decision-support platform, providing all countries on the continent with planning and monitoring tools to achieve Land Degradation Neutrality (LDN).',
   '/ldn.webp', 'https://ldn-africa.oss-online.org/', 8, true),

  (1, 'Readiness Eritrea', 'Readiness Eritrea',
   'Une plateforme d''aide à la décision dédiée aux acteurs érythréens, développée dans le cadre du projet Readiness pour appuyer la planification environnementale et le suivi des actions sur le terrain.',
   'A decision-support platform dedicated to Eritrean stakeholders, developed under the Readiness project to support environmental planning and monitoring of field actions.',
   '/readiness-eritrea.webp', 'https://readiness-ery.oss-online.org/', 9, true);


-- ── Team — Direction ──
-- Members are displayed by id; the first Direction member is featured separately.
INSERT INTO team (name, title_fr, title_en, diplomas_fr, diplomas_en, nationality_fr, nationality_en, image, department) VALUES
  ('M. Nabil BEN KHATRA',
   'Secrétaire Exécutif',
   'Executive Secretary',
   'Agronome et spécialiste en télédétection',
   'Agronomist and remote sensing specialist',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/NbK200.jpg',
   'direction'),

  ('M. Mourad BRIKI',
   'Directeur du Département Communication et Savoir',
   'Director of the Communication and Knowledge Department',
   'Ingénieur Ecologue',
   'Ecological Engineer',
   'Algérienne', 'Algerian',
   'https://www.oss-online.org/sites/default/files/2022-02/_MB200.jpg',
   'direction'),

  ('M. Abina Abdoulkarim BELLO',
   'Directeur du Département Terre et Biodiversité par intérim',
   'Acting Director of the Land and Biodiversity Department',
   'DEA en Science de la production animale',
   'Advanced Studies Diploma (DEA) in Animal Production Science',
   'Nigérienne', 'Nigerien',
   'https://www.oss-online.org/sites/default/files/2026-02/Bello200.jpg',
   'direction'),

  ('Mme Khaoula JAOUI',
   'Coordinatrice des Programmes Techniques, Directrice du Département Climat, et Directrice du Département Développement et Mobilisation',
   'Technical Programmes Coordinator, Director of the Climate Department, and Director of the Development and Resource Mobilization Department',
   'Experte en Finance Climatique et GRN',
   'Climate Finance and Natural Resource Management Expert',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-08/KhaoulaJaoui.jpg',
   'direction'),

  ('M. Nabil HAMADA',
   'Directeur du Département administratif et financier',
   'Director of the Administrative and Financial Department',
   'Ingénieur Général, Forêt, Ecologie et GRN',
   'Chief Engineer in Forestry, Ecology and Natural Resource Management',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/N-Hamada.jpg',
   'direction'),

  ('M. Mohamedou SY',
   'Directeur du Département Eau',
   'Director of the Water Department',
   'Dr. en Hydrogéologie',
   'PhD in Hydrogeology',
   'Mauritanienne', 'Mauritanian',
   'https://www.oss-online.org/sites/default/files/2024-01/BabaSy.jpg',
   'direction'),

  ('M. Mustapha MIMOUNI',
   'Département Veille & Prospective, Data et Plateforme Numérique',
   'Foresight and Prospective, Data and Digital Platform Department',
   'Expert en Télédétection',
   'Remote Sensing Expert',
   'Algérienne', 'Algerian',
   'https://www.oss-online.org/sites/default/files/2024-01/Mustapha200.jpg',
   'direction'),

  ('M. Adel REKIK',
   'Auditeur Interne',
   'Internal Auditor',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Adel-R.png',
   'direction');


-- ── Team — Technique ──
INSERT INTO team (name, title_fr, title_en, diplomas_fr, diplomas_en, nationality_fr, nationality_en, image, department) VALUES
  ('Mme Abir BEN ROMDHANE',
   'Cheffe de la Division de la Biodiversité et des Ecosystèmes',
   'Head of the Biodiversity and Ecosystems Division',
   'Dr. en géologie',
   'PhD in Geology',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-02/Abir%201.jpg',
   'technique'),

  ('M. Evence LOUIS ZOUNGRANA',
   'Chef de la Division Systèmes d’Information & Géomatique',
   'Head of the Information Systems and Geomatics Division',
   'Géographe, expert en SIG, TD et Suivi-Evaluation, Dr. en Sciences Agronomiques',
   'Geographer, expert in GIS, remote sensing and monitoring and evaluation, PhD in Agricultural Sciences',
   'Burkinabè', 'Burkinabè',
   'https://www.oss-online.org/sites/default/files/2022-02/Zoungrana_0.jpg',
   'technique'),

  ('M. Youssouf AMADOU',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Spécialiste de Développement Durable',
   'Sustainable Development Specialist',
   'Centrafricaine', 'Central African',
   'https://www.oss-online.org/sites/default/files/2022-02/Youssouf200_0.jpg',
   'technique'),

  ('M. Haithem RAJEB',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Ingénieur en Génie Hydraulique et Environnement',
   'Hydraulic and Environmental Engineer',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Haithem200_0.jpg',
   'technique'),

  ('M. Steve MUHANJI',
   'Chef de la Division du Développement et du Montage de projets',
   'Head of the Project Development and Design Division',
   'Master en Sciences de l''Environnement et de la GRN',
   'Master''s degree in Environmental Sciences and Natural Resource Management',
   'Kényane', 'Kenyan',
   'https://www.oss-online.org/sites/default/files/2024-03/SteveMuhanji_0.jpg',
   'technique'),

  ('M. Hamda FOUGHALI',
   'Chef de la Division du Renforcement des Capacités',
   'Head of the Capacity Building Division',
   'Master en géomatique d’ingénieur',
   'Master''s degree in Engineering Geomatics',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Hamda_0.jpg',
   'technique'),

  ('M. Amjed HADJ TAIEB',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Ingénieur en GRN, Géo-information dans la gestion de l''environnement',
   'Natural Resource Management Engineer, Geo-information in Environmental Management',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Amjed200_0.jpg',
   'technique'),

  ('M. Aziz BELHAMRA',
   'Chef de la Division de l’Adaptation et de l’Atténuation',
   'Head of the Adaptation and Mitigation Division',
   'Ingénieur agronome, Master en Lutte Contre la Désertification',
   'Agricultural Engineer, Master''s degree in Combating Desertification',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2024-01/Aziz.jpg',
   'technique'),

  ('M. Robert David ONYANGO',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Dr. en changement climatique et adaptation',
   'PhD in Climate Change and Adaptation',
   'Kényane', 'Kenyan',
   'https://www.oss-online.org/sites/default/files/2025-12/Robert-New.jpg',
   'technique'),

  ('M. Omar ENNAIFER',
   'Chef de l’Unité de la conformité et de l’intégrité',
   'Head of the Compliance and Integrity Unit',
   'Biologiste avec spécialisation en Evolution, Ecologie et Environnement',
   'Biologist specializing in Evolution, Ecology and Environment',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Omar200.jpg',
   'technique'),

  ('Mme Leila BENNANI',
   'Chargée de Communication',
   'Communications Officer',
   'Spécialiste en stratégie de communication et contenus multimédias',
   'Specialist in Communication Strategy and Multimedia Content',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/leila_bennani.jpg',
   'technique'),

  ('Mme Olfa OTHMAN',
   'Cheffe de la Division des Publications et de la Gestion des Savoirs',
   'Head of the Publications and Knowledge Management Division',
   'Maîtrise en DBA',
   'Master''s degree in DBA',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-06/Olfa.jpg',
   'technique'),

  ('Mme Kaouther HAMROUNI',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Dr. en Agronomie',
   'PhD in Agronomy',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Kaouther.jpg',
   'technique'),

  ('Mme Olfa Karous',
   'Cheffe de Division Veille et Prospective par intérim',
   'Acting Head of the Foresight and Prospective Division',
   'Ingénieure-Dr. en sciences agronomiques',
   'Engineer and PhD in Agricultural Sciences',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2023-10/OlfaKarous.jpg',
   'technique'),

  ('M. Mohamed AZZABI',
   'Chargé du Parc Informatique',
   'IT Infrastructure Officer',
   'Ingénieur Système d''Information',
   'Information Systems Engineer',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-09/MA_1.jpg',
   'technique'),

  ('Mme Wafa Ameur',
   'Assistante Technique',
   'Technical Assistant',
   'Dr. en sciences agronomiques et environnementales',
   'PhD in Agricultural and Environmental Sciences',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2023-10/WafaAmeur.jpg',
   'technique'),

  ('M. Aymen BENAHMED',
   'Assistant Technique',
   'Technical Assistant',
   'Ingénieur Agronome, Master de recherche en Géomatique Appliquée à l’Agr. et à l’Env.',
   'Agricultural Engineer, Research Master''s degree in Geomatics Applied to Agriculture and the Environment',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2024-12/AymenBENAHMED.jpg',
   'technique'),

  ('M. Khaled LACHAAL',
   'Chef de la Division Data, IA et Innovation',
   'Head of the Data, AI and Innovation Division',
   'Master en Sécurité des Systèmes d''Information',
   'Master''s degree in Information Systems Security',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-06/khaled.jpg',
   'technique'),

  ('Mme Safa ARFAOUI',
   'Assistante technique',
   'Technical Assistant',
   'Ingénieure Agronome, Master en Conservation et Restauration des Ecosystèmes Marins',
   'Agricultural Engineer, Master''s degree in Marine Ecosystem Conservation and Restoration',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2024-12/SafaARFAOUI_0.jpg',
   'technique'),

  ('M. Pouwédéou KAMBIA',
   'Responsable de Gestion de Projets',
   'Project Management Officer',
   'Master en Télédétection et en Systèmes d''Information Géographique',
   'Master''s degree in Remote Sensing and Geographic Information Systems',
   'Togolaise', 'Togolese',
   'https://www.oss-online.org/sites/default/files/2024-12/Kambia.jpg',
   'technique'),

  ('M. Youssef HADDOUK',
   'Chargé de la sécurité des Systèmes d''Information',
   'Information Systems Security Officer',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-05/Youssef-Haddouk.jpg',
   'technique'),

  ('Mme Soumaya MOUHLI',
   'Cheffe de la Division de l’Hydrologie et des Eaux Partagées',
   'Head of the Hydrology and Shared Waters Division',
   'Ingénieure en Hydraulique',
   'Hydraulic Engineer',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-09/Soumaya%20FB.png',
   'technique'),

  ('M. Pape Ndiaye',
   'Chef de la Division de la Communication Institutionnelle',
   'Head of the Institutional Communication Division',
   'Master en Communication des Organisations',
   'Master''s degree in Organizational Communication',
   'Sénégalo-française', 'Senegalese-French',
   'https://www.oss-online.org/sites/default/files/2026-01/Pape.png',
   'technique'),

  ('M. Mehdi CHEBBI',
   'Ingénieur DevOps',
   'DevOps Engineer',
   'Ingénierie en Informatique',
   'Computer Engineering',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-05/Mehdi.jpg',
   'technique'),

  ('Mme Nadia KHAMMARI',
   'Cheffe de l’Unité Partenariats et Plaidoyer',
   'Head of the Partnerships and Advocacy Unit',
   'Master en lettres françaises modernes, Arts et Spectacles',
   'Master''s degree in Modern French Literature, Arts and Performing Arts',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-06/NadiaKh200.png',
   'technique');


-- ── Team — Administratif ──
INSERT INTO team (name, title_fr, title_en, diplomas_fr, diplomas_en, nationality_fr, nationality_en, image, department) VALUES
  ('Mme Sonia ABASSI',
   'Cheffe de l’Unité des Relations Extérieures',
   'Head of the External Relations Unit',
   'Maîtrise Combinée de Langues (MCL)',
   'Combined Languages Degree (MCL)',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Sonia-A.jpg',
   'administratif'),

  ('Mme Souhir BEN HEDIA',
   'Responsable des Affaires Sociales et Logistiques',
   'Social Affairs and Logistics Officer',
   'Maîtrise en droit privé',
   'Degree in Private Law',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Souhir.png',
   'administratif'),

  ('Mme Sonia NJAH',
   'Cheffe de la Division des Affaires Administratives et des Moyens Généraux',
   'Head of the Administrative Affairs and General Services Division',
   'Maîtrise en Economie et Relations Internationales',
   'Degree in Economics and International Relations',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/_SoniaNjah.jpg',
   'administratif'),

  ('Mme Nadia MATHLOUTHI',
   'Agent d''accueil',
   'Receptionist',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Nadia-M.jpg',
   'administratif'),

  ('M. Rafik ZIADI',
   'Chef de la Division de la Comptabilité',
   'Head of the Accounting Division',
   'Maîtrise en Gestion Comptable',
   'Degree in Accounting Management',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Rafik-1.jpg',
   'administratif'),

  ('Mme Henda BELKHODJA',
   'Assistante Administrative',
   'Administrative Assistant',
   'Licence en Management',
   'Bachelor''s degree in Management',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2024-12/HendaBELKHODJA.jpg',
   'administratif'),

  ('Mme Sarra DARDOUR',
   'Gestionnaire Comptable',
   'Accounting Manager',
   'Diplôme national de Master professionnel en comptabilité',
   'National Professional Master''s Degree in Accounting',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2025-05/Sarra-Dardour.jpg',
   'administratif'),

  ('M. Karim BEN TRAD',
   'Chef de la Division des Ressources Humaines',
   'Head of the Human Resources Division',
   'Ecole Nationale d''Administration',
   'National School of Administration',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-01/KarimTrad.jpg',
   'administratif'),

  ('Mme Hayet Dorii',
   'Assistante administrative',
   'Administrative Assistant',
   '', '',
   'Tunisienne', 'Tunisian',
   '',
   'administratif'),

  ('M. Tarek LARBI',
   'Responsable Fiduciaire',
   'Fiduciary Officer',
   'Maîtrise en gestion, marketing',
   'Degree in Management and Marketing',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-06/Tarek-Larbi.jpg',
   'administratif'),

  ('M. Zied SEDIRI',
   'Responsable Financier',
   'Financial Officer',
   'Master professionnel en ingénierie financière et finance d''entreprise',
   'Professional Master''s Degree in Financial Engineering and Corporate Finance',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-06/ZiedSediri.jpg',
   'administratif');


-- ── Team — Appui ──
INSERT INTO team (name, title_fr, title_en, diplomas_fr, diplomas_en, nationality_fr, nationality_en, image, department) VALUES
  ('Mme Souad NAKAA',
   'Agent d''entretien',
   'Maintenance Worker',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Souad.jpg',
   'appui'),

  ('M. Fathi ELLALI',
   'Chauffeur',
   'Driver',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Fethi.jpg',
   'appui'),

  ('Mme Najeh EL HADJ AHMED',
   'Agent d''entretien',
   'Maintenance Worker',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2022-02/Najeh.jpg',
   'appui'),

  ('M. Achref OUERTANI',
   'Chauffeur - Agent de liaison',
   'Driver - Liaison Officer',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-01/Achraf-2.jpg',
   'appui'),

  ('M. Louay AZIZI',
   'Factotum',
   'General Assistant',
   '', '',
   'Tunisienne', 'Tunisian',
   'https://www.oss-online.org/sites/default/files/2026-01/Louay.jpg',
   'appui'),

  ('Mme Mouna ALLAGUI',
   'Agent d''entretien',
   'Maintenance Worker',
   '', '',
   'Tunisienne', 'Tunisian',
   '',
   'appui');


-- ── Socials ──
INSERT INTO socials (platform, url, icon_svg, sort_order) VALUES
  ('facebook',  '#', 'M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z', 1),

  ('x',         '#', 'M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z', 2),

  ('linkedin',  '#', 'M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z', 3),

  ('youtube',   '#', 'M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z', 4),

  ('instagram', '#', 'M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z', 5);
